### ISSUE TITLE
String method: transform

### ISSUE THREAD

**Issue by ArmandoRosasB** [ArmandoRosasB/Java#1]
The transform method is not working.
Check the file: Inmutabilidad.java

```
// transform
        curso.transform((c) -> {
            return c + " con el alumno " + alumno;
        });
        System.out.println("Curso = " + curso);

        String resultado2 = curso.transform((c) -> {
            return c + " con el alumno " + alumno;
        });

        System.out.println("Resultado2 = " + resultado2);
```

Ramona send help!!!

**Comment by RamonaNF** [comment]
Check your jdk version
`java -version`

| jdk 11 | jdk 17 |
| --- | --- |
|![jdk11](https://github.com/ArmandoRosasB/Java/assets/91426086/80448325-256e-450a-b0d3-827ac18ea453)|![jdk17](https://github.com/ArmandoRosasB/Java/assets/91426086/4ec7c9ad-3dbe-4e4d-b301-fb6ebe7501c9)|

[Install OpenJDK 17 on Ubuntu 22.04](https://www.itzgeek.com/how-tos/linux/ubuntu-how-tos/install-java-jdk-17-on-ubuntu-22-04.html)
`sudo apt install -y openjdk-17-jdk`
`sudo apt install -y openjdk-17-jre`

Try compiling again!!
> Visual still flags an error, though

![Inmutabilidad](https://github.com/ArmandoRosasB/Java/assets/91426086/e505f77d-f861-4426-b977-1d14b23bc6ab)

**Comment by ArmandoRosasB** [comment]
Works!!!
